import Head from 'next/head'
import Header from './components/Header'
import Links from './components/Links'
import Bio from './components/Bio'
import Bg from './components/Bg'
import Patients from './components/patients'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Vanderlei Moraes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Bg />
        <Header />
        <Links />
        <Bio />
        <Patients />
      </main>

    </div>
  )
}
